<?php

define('DIARY_CREATED', 101);
define('DIARY_FAILURE', 103);
define('DIARY_ALREADY_INSERTED', 104);

define('DIARY_NOT_FILLED', 101);
define('DIARY_FILL_FAILURE', 103);
define('DIARY_ALREADY_FILLED', 104);